# 11장 데이터 분석을 위한 패키지

## 11.1 배열 데이터를 효과적으로 다루는 NumPy

### 배열 생성하기

**[11장: 215페이지]**

In [1]:
import numpy as np

#### 시퀀스 데이터로부터 배열 생성

**[11장: 215 ~ 216페이지]**

In [2]:
import numpy as np

data1 = [0, 1, 2, 3, 4, 5]
a1 = np.array(data1)
a1

array([0, 1, 2, 3, 4, 5])

**[11장: 216페이지]**

In [3]:
data2 = [0.1, 5, 4, 12, 0.5]
a2 = np.array(data2)
a2

array([ 0.1,  5. ,  4. , 12. ,  0.5])

**[11장: 216페이지]**

In [4]:
a1.dtype

dtype('int64')

In [5]:
a2.dtype

dtype('float64')

**[11장: 216페이지]**

In [6]:
np.array([0.5, 2, 0.01, 8])

array([0.5 , 2.  , 0.01, 8.  ])

**[11장: 217페이지]**

In [7]:
np.array([[1,2,3], [4,5,6], [7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### 범위를 지정해 배열 생성

**[11장: 217페이지]**

In [8]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [9]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(5)

array([0, 1, 2, 3, 4])

**[11장: 218페이지]**

In [11]:
np.arange(12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

**[11장: 218페이지]**

In [12]:
b1 = np.arange(12).reshape(4,3)
b1.shape

(4, 3)

**[11장: 219페이지]**

In [13]:
b2 = np.arange(5)
b2.shape

(5,)

**[11장: 219페이지]**

In [14]:
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

**[11장: 219페이지]**

In [15]:
np.linspace(0, np.pi, 20 )

array([0.        , 0.16534698, 0.33069396, 0.49604095, 0.66138793,
       0.82673491, 0.99208189, 1.15742887, 1.32277585, 1.48812284,
       1.65346982, 1.8188168 , 1.98416378, 2.14951076, 2.31485774,
       2.48020473, 2.64555171, 2.81089869, 2.97624567, 3.14159265])

#### 특별한 형태의 배열 생성

**[11장: 220페이지]**

In [16]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**[11장: 220페이지]**

In [17]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

**[11장: 220 ~ 221페이지]**

In [18]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [19]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

**[11장: 221페이지]**

In [20]:
np.eye(3) # 단위 행렬

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 배열의 데이터 타입 변환

**[11장: 221페이지]**

In [21]:
np.array(['1.5', '0.62', '2', '3.14', '3.141592'])

array(['1.5', '0.62', '2', '3.14', '3.141592'], dtype='<U8')

**[11장: 222페이지]**

In [22]:
str_a1 = np.array(['1.567', '0.123', '5.123', '9', '8'])
num_a1 = str_a1.astype(float)
num_a1

array([1.567, 0.123, 5.123, 9.   , 8.   ])

**[11장: 223페이지]**

In [23]:
str_a1.dtype

dtype('<U5')

In [24]:
num_a1.dtype

dtype('float64')

**[11장: 223페이지]**

In [25]:
str_a2 = np.array(['1', '3', '5', '7', '9'])
num_a2 = str_a2.astype(int)
num_a2

array([1, 3, 5, 7, 9])

**[11장: 223페이지]**

In [26]:
str_a2.dtype

dtype('<U1')

In [27]:
num_a2.dtype

dtype('int64')

**[11장: 223페이지]**

In [28]:
num_f1 = np.array([10, 21, 0.549, 4.75, 5.98])
num_i1 = num_f1.astype(int)
num_i1

array([10, 21,  0,  4,  5])

**[11장: 224페이지]**

In [29]:
num_f1.dtype

dtype('float64')

In [30]:
num_i1.dtype

dtype('int64')

#### 난수 배열의 생성

**[11장: 224 ~ 225페이지]**

In [31]:
np.random.rand(2,3)

array([[0.02770039, 0.19536223, 0.43002633],
       [0.97697968, 0.06893394, 0.85546021]])

In [32]:
np.random.rand()

0.259579800677603

In [33]:
np.random.rand(2,3,4)  # 2x3x4

array([[[0.85573144, 0.38137858, 0.42075621, 0.31480702],
        [0.7672618 , 0.90371743, 0.28268515, 0.42496033],
        [0.86412132, 0.66246795, 0.99778956, 0.7646745 ]],

       [[0.03162085, 0.53312499, 0.5453347 , 0.43407245],
        [0.81581647, 0.1320983 , 0.9024186 , 0.94181632],
        [0.32310471, 0.06664405, 0.42985293, 0.70310746]]])

**[11장: 225페이지]**

In [34]:
np.random.randint(10, size=(3, 4))

array([[5, 0, 2, 9],
       [6, 1, 6, 0],
       [9, 8, 6, 2]])

In [35]:
np.random.randint(1, 30)

15

### 배열의 연산

#### 기본 연산

**[11장: 225페이지]**

In [36]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])

**[11장: 226페이지]**

In [37]:
arr1 + arr2

array([11, 22, 33, 44])

**[11장: 226페이지]**

In [38]:
arr1 - arr2

array([ 9, 18, 27, 36])

**[11장: 226페이지]**

In [39]:
arr2 * 2

array([2, 4, 6, 8])

**[11장: 226페이지]**

In [40]:
arr2 ** 2

array([ 1,  4,  9, 16])

**[11장: 226페이지]**

In [41]:
arr1 * arr2

array([ 10,  40,  90, 160])

**[11장: 227페이지]**

In [42]:
arr1 / arr2

array([10., 10., 10., 10.])

**[11장: 227페이지]**

In [43]:
arr1 / (arr2 ** 2)

array([10.        ,  5.        ,  3.33333333,  2.5       ])

**[11장: 227페이지]**

In [44]:
arr1 > 20

array([False, False,  True,  True])

#### 통계를 위한 연산

**[11장: 227페이지]**

In [45]:
arr3 = np.arange(5)
arr3

array([0, 1, 2, 3, 4])

**[11장: 227페이지]**

In [46]:
[arr3.sum(), arr3.mean()]

[10, 2.0]

**[11장: 228페이지]**

In [47]:
[arr3.std(), arr3.var()]

[1.4142135623730951, 2.0]

**[11장: 228페이지]**

In [48]:
[arr3.min(), arr3.max()]

[0, 4]

**[11장: 228페이지]**

In [49]:
arr4 = np.arange(1,5)
arr4

array([1, 2, 3, 4])

**[11장: 228페이지]** 

In [50]:
arr4.cumsum()

array([ 1,  3,  6, 10])

In [51]:
arr4.cumprod()

array([ 1,  2,  6, 24])

#### 행렬 연산

**[11장: 229페이지]**

In [52]:
A = np.array([0, 1, 2, 3]).reshape(2,2)
A

array([[0, 1],
       [2, 3]])

In [53]:
B = np.array([3, 2, 0, 1]).reshape(2,2)
B

array([[3, 2],
       [0, 1]])

**[11장: 229페이지]**

In [54]:
A.dot(B)  # 내적

array([[0, 1],
       [6, 7]])

In [55]:
np.dot(A,B)

array([[0, 1],
       [6, 7]])

**[11장: 229 ~ 230페이지]**

In [56]:
np.transpose(A)

array([[0, 2],
       [1, 3]])

In [57]:
A.transpose()

array([[0, 2],
       [1, 3]])

**[11장: 230페이지]**

In [58]:
np.linalg.inv(A)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

**[11장: 230페이지]**

In [59]:
np.linalg.det(A)

-2.0

### 배열의 인덱싱과 슬라이싱

#### 배열의 인덱싱

**[11장: 230페이지]**

In [60]:
a1 = np.array([0, 10, 20, 30, 40, 50])
a1

array([ 0, 10, 20, 30, 40, 50])

**[11장: 231페이지]**

In [61]:
a1[0]

0

**[11장: 231페이지]**

In [62]:
a1[4]

40

**[11장: 231페이지]**

In [63]:
a1[5] = 70
a1

array([ 0, 10, 20, 30, 40, 70])

**[11장: 231페이지]**

In [64]:
a1[[1,3,4]]

array([10, 30, 40])

**[11장: 232페이지]**

In [65]:
a2 = np.arange(10, 100, 10).reshape(3,3)
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

**[11장: 232페이지]**

In [66]:
a2[0, 2]

30

**[11장: 232페이지]**

In [67]:
a2[2, 2] = 95
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 95]])

**[11장: 232페이지]**

In [68]:
a2[1]

array([40, 50, 60])

**[11장: 232 ~ 233페이지]**

In [69]:
a2[1] = np.array([45, 55, 65])
a2

array([[10, 20, 30],
       [45, 55, 65],
       [70, 80, 95]])

In [70]:
a2[1] = [47, 57, 67]
a2

array([[10, 20, 30],
       [47, 57, 67],
       [70, 80, 95]])

**[11장: 233페이지]**

In [71]:
a2[[0, 2], [0, 1]]

array([10, 80])

**[11장: 233페이지]**

In [72]:
a = np.array([1, 2, 3, 4, 5, 6])
a[a > 3]

array([4, 5, 6])

**[11장: 234페이지]**

In [73]:
a[(a % 2) == 0]

array([2, 4, 6])

#### 배열의 슬라이싱

**[11장: 234페이지]**

In [74]:
b1 = np.array([0, 10, 20, 30, 40, 50])
b1[1:4]

array([10, 20, 30])

**[11장: 234페이지]**

In [75]:
b1[:3]

array([ 0, 10, 20])

In [76]:
b1[2:]

array([20, 30, 40, 50])

**[11장: 235페이지]**

In [77]:
b1[2:5] = np.array([25, 35, 45])
b1

array([ 0, 10, 25, 35, 45, 50])

**[11장: 235페이지]**

In [78]:
b1[3:6] = 60
b1

array([ 0, 10, 25, 60, 60, 60])

**[11장: 235페이지]**

In [79]:
b2 = np.arange(10, 100, 10).reshape(3,3)
b2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

**[11장: 236페이지]**

In [80]:
b2[1:3, 1:3]

array([[50, 60],
       [80, 90]])

**[11장: 236페이지]**

In [81]:
b2[:3, 1:]

array([[20, 30],
       [50, 60],
       [80, 90]])

**[11장: 236페이지]**

In [82]:
b2[1][0:2]

array([40, 50])

**[11장: 236페이지]**

In [83]:
b2[0:2, 1:3] = np.array([[25, 35], [55, 65]])
b2

array([[10, 25, 35],
       [40, 55, 65],
       [70, 80, 90]])

## 11.2 구조적 데이터 표시와 처리에 강한 pandas

### 구조적 데이터 생성하기

#### Series를 활용한 데이터 생성

**[11장: 237페이지]**

In [84]:
import pandas as pd

**[11장: 238페이지]**

In [85]:
s1 = pd.Series([10, 20, 30, 40, 50])
s1

0    10
1    20
2    30
3    40
4    50
dtype: int64

**[11장: 238페이지]**

In [86]:
s1.index
print(s1.index)

RangeIndex(start=0, stop=5, step=1)


**[11장: 239페이지]**

In [87]:
s1.values

array([10, 20, 30, 40, 50])

**[11장: 239페이지]**

In [88]:
s2 = pd.Series(['a', 'b', 'c', 1, 2, 3]) # 세로축:인덱스/가로측:VALUE
s2

0    a
1    b
2    c
3    1
4    2
5    3
dtype: object

**[11장: 239페이지]**

In [89]:
import numpy as np

s3 = pd.Series([np.nan,10,30]) # np.nan:값이 없다
s3

0     NaN
1    10.0
2    30.0
dtype: float64

**[11장: 240페이지]**

In [90]:
# 날자와 판매량을 series 형식으로 변환(데이터 갯수가 같아야 함)
index_date = ['2018-10-07','2018-10-08','2018-10-09','2018-10-10']
s4 = pd.Series([200, 195, np.nan, 205], index = index_date)
s4

2018-10-07    200.0
2018-10-08    195.0
2018-10-09      NaN
2018-10-10    205.0
dtype: float64

**[11장: 241페이지]**

In [91]:
# 딕트의 series 변경(key-Index:value-value)
s5 = pd.Series({'국어': 100, '영어': 95, '수학': 90})
s5

국어    100
영어     95
수학     90
dtype: int64

#### 날짜 자동 생성: date_range

pd.date_range(start = , end =, periods = , freq = )

**[11장: 241페이지]**

In [92]:
import pandas as pd

pd.date_range(start='2019-01-01',end='2019-01-07')

DatetimeIndex(['2019-01-01', '2019-01-02', '2019-01-03', '2019-01-04',
               '2019-01-05', '2019-01-06', '2019-01-07'],
              dtype='datetime64[ns]', freq='D')

**[11장: 242페이지]**

In [93]:
pd.date_range(start='2019/01/01',end='2019.01.07')

DatetimeIndex(['2019-01-01', '2019-01-02', '2019-01-03', '2019-01-04',
               '2019-01-05', '2019-01-06', '2019-01-07'],
              dtype='datetime64[ns]', freq='D')

In [94]:
pd.date_range(start='01-01-2019',end='01/07/2019')

DatetimeIndex(['2019-01-01', '2019-01-02', '2019-01-03', '2019-01-04',
               '2019-01-05', '2019-01-06', '2019-01-07'],
              dtype='datetime64[ns]', freq='D')

In [95]:
pd.date_range(start='2019-01-01',end='01.07.2019')

DatetimeIndex(['2019-01-01', '2019-01-02', '2019-01-03', '2019-01-04',
               '2019-01-05', '2019-01-06', '2019-01-07'],
              dtype='datetime64[ns]', freq='D')

**[11장: 242페이지]**

In [96]:
pd.date_range(start='2019-01-01', periods = 7)  # 7일

DatetimeIndex(['2019-01-01', '2019-01-02', '2019-01-03', '2019-01-04',
               '2019-01-05', '2019-01-06', '2019-01-07'],
              dtype='datetime64[ns]', freq='D')

**[11장: 243페이지]**

In [97]:
pd.date_range(start='2019-01-01', periods = 4, freq = '2D')  # 4일, 2일 간격으로

DatetimeIndex(['2019-01-01', '2019-01-03', '2019-01-05', '2019-01-07'], dtype='datetime64[ns]', freq='2D')

**[11장: 244페이지]**

In [98]:
pd.date_range(start='2019-01-01', periods = 4, freq = 'W')  # 4일, 일주일 간격으로

DatetimeIndex(['2019-01-06', '2019-01-13', '2019-01-20', '2019-01-27'], dtype='datetime64[ns]', freq='W-SUN')

**[11장: 244페이지]**

In [99]:
# 매월 업무 마감일(월~금)
pd.date_range(start='2023-01-01', periods = 12, freq = '1BM')

DatetimeIndex(['2023-01-31', '2023-02-28', '2023-03-31', '2023-04-28',
               '2023-05-31', '2023-06-30', '2023-07-31', '2023-08-31',
               '2023-09-29', '2023-10-31', '2023-11-30', '2023-12-29'],
              dtype='datetime64[ns]', freq='BM')

**[11장: 244페이지]**

In [100]:
pd.date_range(start='2019-01-01', periods = 4, freq = 'QS')

DatetimeIndex(['2019-01-01', '2019-04-01', '2019-07-01', '2019-10-01'], dtype='datetime64[ns]', freq='QS-JAN')

**[11장: 244페이지]**

In [101]:
pd.date_range(start='2019-01-01', periods = 3, freq = 'AS')

DatetimeIndex(['2019-01-01', '2020-01-01', '2021-01-01'], dtype='datetime64[ns]', freq='AS-JAN')

**[11장: 244페이지]**

In [102]:
pd.date_range(start = '2019-01-01 08:00', periods = 10, freq='H')  # 10개, 1시간 간격으로

DatetimeIndex(['2019-01-01 08:00:00', '2019-01-01 09:00:00',
               '2019-01-01 10:00:00', '2019-01-01 11:00:00',
               '2019-01-01 12:00:00', '2019-01-01 13:00:00',
               '2019-01-01 14:00:00', '2019-01-01 15:00:00',
               '2019-01-01 16:00:00', '2019-01-01 17:00:00'],
              dtype='datetime64[ns]', freq='H')

**[11장: 245페이지]**

In [103]:
pd.date_range(start = '2019-01-01 08:00', periods = 10, freq='BH') #업무시간 09~17시

DatetimeIndex(['2019-01-01 09:00:00', '2019-01-01 10:00:00',
               '2019-01-01 11:00:00', '2019-01-01 12:00:00',
               '2019-01-01 13:00:00', '2019-01-01 14:00:00',
               '2019-01-01 15:00:00', '2019-01-01 16:00:00',
               '2019-01-02 09:00:00', '2019-01-02 10:00:00'],
              dtype='datetime64[ns]', freq='BH')

**[11장: 245페이지]**

In [104]:
pd.date_range(start = '2019-01-01 10:00', periods = 4, freq='30min')

DatetimeIndex(['2019-01-01 10:00:00', '2019-01-01 10:30:00',
               '2019-01-01 11:00:00', '2019-01-01 11:30:00'],
              dtype='datetime64[ns]', freq='30T')

**[11장: 245페이지]**

In [105]:
# 위와 동일
pd.date_range(start = '2019-01-01 10:00', periods = 4, freq='30T')

DatetimeIndex(['2019-01-01 10:00:00', '2019-01-01 10:30:00',
               '2019-01-01 11:00:00', '2019-01-01 11:30:00'],
              dtype='datetime64[ns]', freq='30T')

**[11장: 246페이지]**

In [106]:
pd.date_range(start = '2019-01-01 10:00:00', periods = 4, freq='10S')

DatetimeIndex(['2019-01-01 10:00:00', '2019-01-01 10:00:10',
               '2019-01-01 10:00:20', '2019-01-01 10:00:30'],
              dtype='datetime64[ns]', freq='10S')

**[11장: 246페이지]**

In [107]:
index_date = pd.date_range(start = '2019-03-01', periods = 5, freq='D')
pd.Series([51, 62, 55, 49, 58], index = index_date )

2019-03-01    51
2019-03-02    62
2019-03-03    55
2019-03-04    49
2019-03-05    58
Freq: D, dtype: int64

#### DataFrame을 활용한 데이터 생성

**[11장: 247페이지]**

In [108]:
import pandas as pd

pd.DataFrame([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

**[11장: 248페이지]**

In [109]:
import numpy as np
import pandas as pd

data_list = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
pd.DataFrame(data_list)

0   1   2
0  10  20  30
1  40  50  60
2  70  80  90

**[11장: 248페이지]**

In [110]:
import numpy as np
import pandas as pd

data = np.array([[1, 2, 3], [4, 5, 6], [7, 8 ,9], [10, 11, 12]])
index_date = pd.date_range('2019-09-01', periods=4)
columns_list = ['A', 'B', 'C']  # 속성명

pd.DataFrame(data, index=index_date, columns=columns_list)

A   B   C
2019-09-01   1   2   3
2019-09-02   4   5   6
2019-09-03   7   8   9
2019-09-04  10  11  12

**[11장: 249페이지]**

In [111]:
table_data = {'연도': [2015, 2016, 2016, 2017, 2017],
              '지사': ['한국', '한국', '미국', '한국','미국'],
              '고객 수': [200, 250, 450, 300, 500]}
table_data

{'연도': [2015, 2016, 2016, 2017, 2017],
 '지사': ['한국', '한국', '미국', '한국', '미국'],
 '고객 수': [200, 250, 450, 300, 500]}

**[11장: 249페이지]**

In [112]:
pd.DataFrame(table_data)

연도  지사  고객 수
0  2015  한국   200
1  2016  한국   250
2  2016  미국   450
3  2017  한국   300
4  2017  미국   500

**[11장: 250페이지]**

In [113]:
df = pd.DataFrame(table_data, columns=['연도', '지사', '고객 수'])  # 속성명 변경 가능
df

연도  지사  고객 수
0  2015  한국   200
1  2016  한국   250
2  2016  미국   450
3  2017  한국   300
4  2017  미국   500

**[11장: 251페이지]**

In [114]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [124]:
df.columns

Index(['연도', '지사', '고객 수'], dtype='object')

In [125]:
df.values

array([[2015, '한국', 200],
       [2016, '한국', 250],
       [2016, '미국', 450],
       [2017, '한국', 300],
       [2017, '미국', 500]], dtype=object)

### 데이터 연산

**[11장: 251 ~ 252페이지]**

In [126]:
s1 = pd.Series([1, 2, 3, 4, 5])
s2 = pd.Series([10, 20, 30, 40, 50])
s1 + s2

0    11
1    22
2    33
3    44
4    55
dtype: int64

In [127]:
s2 - s1

0     9
1    18
2    27
3    36
4    45
dtype: int64

In [128]:
s1 * s2

0     10
1     40
2     90
3    160
4    250
dtype: int64

In [129]:
s2 / s1

0    10.0
1    10.0
2    10.0
3    10.0
4    10.0
dtype: float64

**[11장: 252 ~ 253페이지]**

In [130]:
s3 = pd.Series([1, 2, 3, 4])
s4 = pd.Series([10, 20, 30, 40, 50])
s3 + s4

0    11.0
1    22.0
2    33.0
3    44.0
4     NaN
dtype: float64

In [131]:
s4 - s3

0     9.0
1    18.0
2    27.0
3    36.0
4     NaN
dtype: float64

In [132]:
s3 * s4

0     10.0
1     40.0
2     90.0
3    160.0
4      NaN
dtype: float64

In [133]:
s4/s3

0    10.0
1    10.0
2    10.0
3    10.0
4     NaN
dtype: float64

**[11장: 253 ~ 254페이지]**

In [134]:
table_data1 = {'A': [1, 2, 3, 4, 5],
              'B': [10, 20, 30, 40, 50],
              'C': [100, 200, 300, 400, 500]}

df1 = pd.DataFrame(table_data1)
df1

A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [135]:
table_data2 = {'A': [6, 7, 8],
              'B': [60, 70, 80],
              'C': [600, 700, 800]}

df2 = pd.DataFrame(table_data2)
df2

A   B    C
0  6  60  600
1  7  70  700
2  8  80  800

**[11장: 254페이지]**

In [136]:
df1 + df2

A      B       C
0   7.0   70.0   700.0
1   9.0   90.0   900.0
2  11.0  110.0  1100.0
3   NaN    NaN     NaN
4   NaN    NaN     NaN

**[11장: 255페이지]**

In [137]:
table_data3 = {'봄':  [256.5, 264.3, 215.9, 223.2, 312.8],
              '여름': [770.6, 567.5, 599.8, 387.1, 446.2],
              '가을': [363.5, 231.2, 293.1, 247.7, 381.6],
              '겨울': [139.3, 59.9, 76.9, 109.1, 108.1]}

columns_list = ['봄', '여름', '가을', '겨울']
index_list = ['2012', '2013', '2014', '2015', '2016']

df3 = pd.DataFrame(table_data3, columns = columns_list, index = index_list)
df3

봄     여름     가을     겨울
2012  256.5  770.6  363.5  139.3
2013  264.3  567.5  231.2   59.9
2014  215.9  599.8  293.1   76.9
2015  223.2  387.1  247.7  109.1
2016  312.8  446.2  381.6  108.1

In [139]:
table_data3 = {'봄':  [256.5, 264.3, 215.9, 223.2, 312.8],
              '여름': [770.6, 567.5, 599.8, 387.1, 446.2],
              '가을': [363.5, 231.2, 293.1, 247.7, 381.6],
              '겨울': [139.3, 59.9, 76.9, 109.1, 108.1]}
#columns_list = ['봄', '여름', '가을', '겨울']
index_list = ['2012', '2013', '2014', '2015', '2016']

df3 = pd.DataFrame(table_data3, index = index_list)
df3

봄     여름     가을     겨울
2012  256.5  770.6  363.5  139.3
2013  264.3  567.5  231.2   59.9
2014  215.9  599.8  293.1   76.9
2015  223.2  387.1  247.7  109.1
2016  312.8  446.2  381.6  108.1

**[11장: 256페이지]**

In [144]:
# df3.mean()
df3.mean(axis=0)

봄     254.54
여름    554.24
가을    303.42
겨울     98.66
dtype: float64

In [145]:
# df3.std()
df3.std(axis=0)

봄      38.628267
여름    148.888895
가을     67.358496
겨울     30.925523
dtype: float64

**[11장: 256 ~ 257페이지]**

In [142]:
df3.mean(axis=1)

2012    382.475
2013    280.725
2014    296.425
2015    241.775
2016    312.175
dtype: float64

In [143]:
df3.std(axis=1)

2012    274.472128
2013    211.128782
2014    221.150739
2015    114.166760
2016    146.548658
dtype: float64

**[11장: 257페이지]**

In [146]:
df3.describe()

봄          여름          가을          겨울
count    5.000000    5.000000    5.000000    5.000000
mean   254.540000  554.240000  303.420000   98.660000
std     38.628267  148.888895   67.358496   30.925523
min    215.900000  387.100000  231.200000   59.900000
25%    223.200000  446.200000  247.700000   76.900000
50%    256.500000  567.500000  293.100000  108.100000
75%    264.300000  599.800000  363.500000  109.100000
max    312.800000  770.600000  381.600000  139.300000

### 데이터를 원하는 대로 선택하기

**[11장: 258페이지]**

In [147]:
import pandas as pd
import numpy as np

KTX_data = {'경부선 KTX': [39060, 39896, 42005, 43621, 41702, 41266, 32427],
            '호남선 KTX': [7313, 6967, 6873, 6626, 8675, 10622, 9228],
            '경전선 KTX': [3627, 4168, 4088, 4424, 4606, 4984, 5570],
            '전라선 KTX': [309, 1771, 1954, 2244, 3146, 3945, 5766],
            '동해선 KTX': [np.nan,np.nan, np.nan, np.nan, 2395, 3786, 6667]}

col_list = ['경부선 KTX','호남선 KTX','경전선 KTX','전라선 KTX','동해선 KTX']
index_list = ['2011', '2012', '2013', '2014', '2015', '2016', '2017']

df_KTX = pd.DataFrame(KTX_data, columns = col_list, index = index_list)
df_KTX

경부선 KTX  호남선 KTX  경전선 KTX  전라선 KTX  동해선 KTX
2011    39060     7313     3627      309      NaN
2012    39896     6967     4168     1771      NaN
2013    42005     6873     4088     1954      NaN
2014    43621     6626     4424     2244      NaN
2015    41702     8675     4606     3146   2395.0
2016    41266    10622     4984     3945   3786.0
2017    32427     9228     5570     5766   6667.0

**[11장: 259페이지]**

In [148]:
df_KTX.index

Index(['2011', '2012', '2013', '2014', '2015', '2016', '2017'], dtype='object')

In [149]:
df_KTX.columns

Index(['경부선 KTX', '호남선 KTX', '경전선 KTX', '전라선 KTX', '동해선 KTX'], dtype='object')

In [150]:
df_KTX.values

array([[39060.,  7313.,  3627.,   309.,    nan],
       [39896.,  6967.,  4168.,  1771.,    nan],
       [42005.,  6873.,  4088.,  1954.,    nan],
       [43621.,  6626.,  4424.,  2244.,    nan],
       [41702.,  8675.,  4606.,  3146.,  2395.],
       [41266., 10622.,  4984.,  3945.,  3786.],
       [32427.,  9228.,  5570.,  5766.,  6667.]])

**[11장: 260페이지]**

In [151]:
df_KTX.head()

경부선 KTX  호남선 KTX  경전선 KTX  전라선 KTX  동해선 KTX
2011    39060     7313     3627      309      NaN
2012    39896     6967     4168     1771      NaN
2013    42005     6873     4088     1954      NaN
2014    43621     6626     4424     2244      NaN
2015    41702     8675     4606     3146   2395.0

In [152]:
df_KTX.tail()

경부선 KTX  호남선 KTX  경전선 KTX  전라선 KTX  동해선 KTX
2013    42005     6873     4088     1954      NaN
2014    43621     6626     4424     2244      NaN
2015    41702     8675     4606     3146   2395.0
2016    41266    10622     4984     3945   3786.0
2017    32427     9228     5570     5766   6667.0

**[11장: 260 ~ 261페이지]**

In [153]:
df_KTX.head(3)  # 3개만

경부선 KTX  호남선 KTX  경전선 KTX  전라선 KTX  동해선 KTX
2011    39060     7313     3627      309      NaN
2012    39896     6967     4168     1771      NaN
2013    42005     6873     4088     1954      NaN

In [154]:
df_KTX.tail(2)

경부선 KTX  호남선 KTX  경전선 KTX  전라선 KTX  동해선 KTX
2016    41266    10622     4984     3945   3786.0
2017    32427     9228     5570     5766   6667.0

**[11장: 261페이지]**

In [155]:
df_KTX[1:2]

경부선 KTX  호남선 KTX  경전선 KTX  전라선 KTX  동해선 KTX
2012    39896     6967     4168     1771      NaN

**[11장: 261페이지]**

In [156]:
df_KTX[2:5]

경부선 KTX  호남선 KTX  경전선 KTX  전라선 KTX  동해선 KTX
2013    42005     6873     4088     1954      NaN
2014    43621     6626     4424     2244      NaN
2015    41702     8675     4606     3146   2395.0

**[11장: 262페이지]**

In [157]:
df_KTX.loc['2011']

경부선 KTX    39060.0
호남선 KTX     7313.0
경전선 KTX     3627.0
전라선 KTX      309.0
동해선 KTX        NaN
Name: 2011, dtype: float64

**[11장: 262페이지]**

In [158]:
df_KTX.loc['2013':'2016']

경부선 KTX  호남선 KTX  경전선 KTX  전라선 KTX  동해선 KTX
2013    42005     6873     4088     1954      NaN
2014    43621     6626     4424     2244      NaN
2015    41702     8675     4606     3146   2395.0
2016    41266    10622     4984     3945   3786.0

**[11장: 263페이지]**

In [159]:
df_KTX['경부선 KTX']

2011    39060
2012    39896
2013    42005
2014    43621
2015    41702
2016    41266
2017    32427
Name: 경부선 KTX, dtype: int64

**[11장: 263페이지]**

In [160]:
df_KTX['경부선 KTX']['2012':'2014']

2012    39896
2013    42005
2014    43621
Name: 경부선 KTX, dtype: int64

**[11장: 264페이지]**

In [161]:
df_KTX['경부선 KTX'][2:5]

2013    42005
2014    43621
2015    41702
Name: 경부선 KTX, dtype: int64

**[11장: 264페이지]**

In [162]:
df_KTX.loc['2016']['호남선 KTX']

10622.0

In [163]:
df_KTX.loc['2016','호남선 KTX']

10622

In [164]:
df_KTX['호남선 KTX']['2016']

10622

In [165]:
df_KTX['호남선 KTX'][5]

10622

In [166]:
df_KTX['호남선 KTX'].loc['2016']

10622

**[11장: 265페이지]**

In [167]:
df_KTX.T  # 행열 전환

2011     2012     2013     2014     2015     2016     2017
경부선 KTX  39060.0  39896.0  42005.0  43621.0  41702.0  41266.0  32427.0
호남선 KTX   7313.0   6967.0   6873.0   6626.0   8675.0  10622.0   9228.0
경전선 KTX   3627.0   4168.0   4088.0   4424.0   4606.0   4984.0   5570.0
전라선 KTX    309.0   1771.0   1954.0   2244.0   3146.0   3945.0   5766.0
동해선 KTX      NaN      NaN      NaN      NaN   2395.0   3786.0   6667.0

**[11장: 265페이지]**

In [168]:
df_KTX

경부선 KTX  호남선 KTX  경전선 KTX  전라선 KTX  동해선 KTX
2011    39060     7313     3627      309      NaN
2012    39896     6967     4168     1771      NaN
2013    42005     6873     4088     1954      NaN
2014    43621     6626     4424     2244      NaN
2015    41702     8675     4606     3146   2395.0
2016    41266    10622     4984     3945   3786.0
2017    32427     9228     5570     5766   6667.0

**[11장: 266페이지]**

In [169]:
df_KTX[['동해선 KTX', '전라선 KTX', '경전선 KTX', '호남선 KTX', '경부선 KTX']]

동해선 KTX  전라선 KTX  경전선 KTX  호남선 KTX  경부선 KTX
2011      NaN      309     3627     7313    39060
2012      NaN     1771     4168     6967    39896
2013      NaN     1954     4088     6873    42005
2014      NaN     2244     4424     6626    43621
2015   2395.0     3146     4606     8675    41702
2016   3786.0     3945     4984    10622    41266
2017   6667.0     5766     5570     9228    32427

### 데이터 통합하기

#### 세로 방향으로 통합하기

**[11장: 267페이지]**

In [1]:
import pandas as pd
import numpy as np

df1 = pd.DataFrame({'Class1': [95, 92, 98, 100],
                    'Class2': [91, 93, 97, 99]})
df1

Class1  Class2
0      95      91
1      92      93
2      98      97
3     100      99

**[11장: 267페이지]**

In [2]:
df2 = pd.DataFrame({'Class1': [87, 89],
                    'Class2': [85, 90]})
df2

Class1  Class2
0      87      85
1      89      90

**[11장: 267페이지]**

In [3]:
df1.append(df2)

/var/folders/tm/z0_l1gjn78z5t_mvlj7t50rh0000gn/T/ipykernel_931/3062608662.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1.append(df2)


Class1  Class2
0      95      91
1      92      93
2      98      97
3     100      99
0      87      85
1      89      90

**[11장: 268페이지]**

In [173]:
df1.append(df2, ignore_index=True)  # df2의 인덱스는 무시

<ipython-input-173-992fb3fde170>:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1.append(df2, ignore_index=True)


Class1  Class2
0      95      91
1      92      93
2      98      97
3     100      99
4      87      85
5      89      90

**[11장: 268페이지]**

In [174]:
df3 = pd.DataFrame({'Class1': [96, 83]})
df3

Class1
0      96
1      83

**[11장: 269페이지]**

In [175]:
df2.append(df3, ignore_index=True)  # df3의 인덱스는 무시

<ipython-input-175-56cff15cce5c>:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2.append(df3, ignore_index=True)


Class1  Class2
0      87    85.0
1      89    90.0
2      96     NaN
3      83     NaN

#### 가로 방향으로 통합하기

**[11장: 269페이지]**

In [176]:
df4 = pd.DataFrame({'Class3': [93, 91, 95, 98]})
df4

Class3
0      93
1      91
2      95
3      98

**[11장: 270페이지]**

In [177]:
df1.join(df4)

Class1  Class2  Class3
0      95      91      93
1      92      93      91
2      98      97      95
3     100      99      98

**[11장: 270페이지]**

In [178]:
index_label = ['a','b','c','d']
df1a = pd.DataFrame({'Class1': [95, 92, 98, 100],
                    'Class2': [91, 93, 97, 99]}, index= index_label)
df4a = pd.DataFrame({'Class3': [93, 91, 95, 98]}, index=index_label)

df1a.join(df4a)

Class1  Class2  Class3
a      95      91      93
b      92      93      91
c      98      97      95
d     100      99      98

**[11장: 270페이지]**

In [179]:
df5 = pd.DataFrame({'Class4': [82, 92]})
df5

Class4
0      82
1      92

**[11장: 271페이지]**

In [180]:
df1.join(df5)

Class1  Class2  Class4
0      95      91    82.0
1      92      93    92.0
2      98      97     NaN
3     100      99     NaN

#### 특정 열을 기준으로 통합하기

**[11장: 271 ~272페이지]**

In [181]:
df_A_B = pd.DataFrame({'판매월': ['1월', '2월', '3월', '4월'],
                       '제품A': [100, 150, 200, 130],
                       '제품B': [90, 110, 140, 170]})
df_A_B

판매월  제품A  제품B
0  1월  100   90
1  2월  150  110
2  3월  200  140
3  4월  130  170

In [182]:
df_C_D = pd.DataFrame({'판매월': ['1월', '2월', '3월', '4월'],
                       '제품C': [112, 141, 203, 134],
                       '제품D': [90, 110, 140, 170]})
df_C_D

판매월  제품C  제품D
0  1월  112   90
1  2월  141  110
2  3월  203  140
3  4월  134  170

**[11장: 272페이지]**

In [183]:
df_A_B.merge(df_C_D)  # 합치기

판매월  제품A  제품B  제품C  제품D
0  1월  100   90  112   90
1  2월  150  110  141  110
2  3월  200  140  203  140
3  4월  130  170  134  170

**[11장: 273페이지]**

In [184]:
df_left = pd.DataFrame({'key':['A','B','C'], 'left': [1, 2, 3]})
df_left

key  left
0   A     1
1   B     2
2   C     3

In [185]:
df_right = pd.DataFrame({'key':['A','B','D'], 'right': [4, 5, 6]})
df_right

key  right
0   A      4
1   B      5
2   D      6

**[11장: 274페이지]**

In [186]:
df_left.merge(df_right, how='left', on = 'key')  # left 기준으로 key 칼럼을 가지고

key  left  right
0   A     1    4.0
1   B     2    5.0
2   C     3    NaN

In [187]:
df_left.merge(df_right, how='right', on = 'key')

key  left  right
0   A   1.0      4
1   B   2.0      5
2   D   NaN      6

In [188]:
df_left.merge(df_right, how='outer', on = 'key')  # outer join

key  left  right
0   A   1.0    4.0
1   B   2.0    5.0
2   C   3.0    NaN
3   D   NaN    6.0

In [189]:
df_left.merge(df_right, how='inner', on = 'key')  # inner join. 공통만

key  left  right
0   A     1      4
1   B     2      5

### 데이터 파일을 읽고 쓰기

#### 표 형식의 데이터 파일을 읽기

**[11장: 276페이지]**

In [4]:
from google.colab import drive
drive.mount('/content/drive')

ModuleNotFoundError: No module named 'google'

In [193]:
cd "/content/drive/MyDrive/2023.04.24~06.30_빅데이터 부트캠프 25기(엔코아 플레이 데이터)/00.판다스(Pandas)/00. [교재]데이터분석을 위한 파이썬 철저 입문(위키북스)_20230428/notebook"

/content/drive/MyDrive/2023.04.24~06.30_빅데이터 부트캠프 25기(엔코아 플레이 데이터)/00.판다스(Pandas)/00. [교재]데이터분석을 위한 파이썬 철저 입문(위키북스)_20230428/notebook


In [5]:
cd /Users/Ahn/2023/Python/00. [교재]데이터분석을 위한 파이썬 철저 입문(위키북스)_20230428/notebook

/Users/Ahn/2023/Python/00. [교재]데이터분석을 위한 파이썬 철저 입문(위키북스)_20230428/notebook


In [195]:
%%writefile sea_rain1.csv
연도,동해,남해,서해,전체
1996,17.4629,17.2288,14.436,15.9067
1997,17.4116,17.4092,14.8248,16.1526
1998,17.5944,18.011,15.2512,16.6044
1999,18.1495,18.3175,14.8979,16.6284
2000,17.9288,18.1766,15.0504,16.6178

Writing sea_rain1.csv


**[11장: 276페이지]**

In [6]:
import pandas as pd

pd.read_csv('./sea_rain1.csv')

연도       동해       남해       서해       전체
0  1996  17.4629  17.2288  14.4360  15.9067
1  1997  17.4116  17.4092  14.8248  16.1526
2  1998  17.5944  18.0110  15.2512  16.6044
3  1999  18.1495  18.3175  14.8979  16.6284
4  2000  17.9288  18.1766  15.0504  16.6178

**[11장: 277페이지]**

In [7]:
pwd

'/Users/Ahn/2023/Python/00. [교재]데이터분석을 위한 파이썬 철저 입문(위키북스)_20230428/notebook'

In [8]:
import os

os.listdir()

['학생시험성적2.xlsx',
 'sea_rain1_from_notepad.csv',
 'word_count.csv',
 '._image___init__.py',
 'littleprince_djvu.txt',
 'total_sales_data.csv',
 '.DS_Store',
 'coffeeShopSales.docx',
 'Chapter_11_NumPy_pandas.ipynb',
 'save_DataFrame_cp949.txt',
 'Chapter_16_Data_analysis.ipynb',
 'two_times_table1.docx',
 '학생시험성적.xlsx',
 '__init__.py',
 '.my_first_module.py',
 'missing_data_test.csv',
 'Chapter_13_Working_with_excel.ipynb',
 'coffeeShopSales.txt',
 'two_times_table(3).docx',
 'sea_rain1_space.txt',
 '담당자별_판매량_Andy사원.xlsx',
 'two_times_table(1).docx',
 'two_times_table.docx',
 'two_times_table1.txt',
 'two_times_table1(2).docx',
 'coffeeShopSales(2).docx',
 'save_DataFrame.csv',
 '담당자별_판매량_Becky사원.xlsx',
 '.ipynb_checkpoints',
 'two_times_table(2).docx',
 'Chapter_12_matplotlib.ipynb',
 'Chapter_13_Working_with_excel_error.ipynb',
 'sea_rain1.csv',
 'coffeeShopSales(1).docx',
 'two_times_table1(1).docx',
 'two_times_table.txt',
 '담당자별_판매량_Chris사원.xlsx',
 'coffeeShopSales(3).docx',
 'two_

In [11]:
pd.read_csv('./sea_rain1_from_notepad.csv', encoding = "cp949")

연도       동해       남해       서해       전체
0  1996  17.4629  17.2288  14.4360  15.9067
1  1997  17.4116  17.4092  14.8248  16.1526
2  1998  17.5944  18.0110  15.2512  16.6044
3  1999  18.1495  18.3175  14.8979  16.6284
4  2000  17.9288  18.1766  15.0504  16.6178

**[11장: 277페이지]**

In [202]:
%%writefile sea_rain1_space.txt
연도 동해 남해 서해 전체
1996 17.4629 17.2288 14.436 15.9067
1997 17.4116 17.4092 14.8248 16.1526
1998 17.5944 18.011 15.2512 16.6044
1999 18.1495 18.3175 14.8979 16.6284
2000 17.9288 18.1766 15.0504 16.6178

Writing sea_rain1_space.txt


**[11장: 278페이지]**

In [203]:
pd.read_csv('./sea_rain1_space.txt', sep=" ")

연도       동해       남해       서해       전체
0  1996  17.4629  17.2288  14.4360  15.9067
1  1997  17.4116  17.4092  14.8248  16.1526
2  1998  17.5944  18.0110  15.2512  16.6044
3  1999  18.1495  18.3175  14.8979  16.6284
4  2000  17.9288  18.1766  15.0504  16.6178

**[11장: 278페이지]**

In [205]:
pd.read_csv('./sea_rain1.csv', index_col="연도" )  # 연도를 인덱스로

동해       남해       서해       전체
연도                                      
1996  17.4629  17.2288  14.4360  15.9067
1997  17.4116  17.4092  14.8248  16.1526
1998  17.5944  18.0110  15.2512  16.6044
1999  18.1495  18.3175  14.8979  16.6284
2000  17.9288  18.1766  15.0504  16.6178

#### 표 형식의 데이터를 파일로 쓰기

**[11장: 279페이지]**

In [12]:
df_WH = pd.DataFrame({'Weight':[62, 67, 55, 74],
                      'Height':[165, 177, 160, 180]},
                       index=['ID_1', 'ID_2', 'ID_3', 'ID_4'])
df_WH.index.name = 'User'
df_WH

Weight  Height
User                
ID_1      62     165
ID_2      67     177
ID_3      55     160
ID_4      74     180

**[11장: 280페이지]**

In [13]:
bmi = df_WH['Weight']/(df_WH['Height']/100)**2
bmi

User
ID_1    22.773186
ID_2    21.385936
ID_3    21.484375
ID_4    22.839506
dtype: float64

**[11장: 280페이지]**

In [14]:
df_WH['BMI'] = bmi
df_WH

Weight  Height        BMI
User                           
ID_1      62     165  22.773186
ID_2      67     177  21.385936
ID_3      55     160  21.484375
ID_4      74     180  22.839506

**[11장: 281페이지]**

In [15]:
df_WH.to_csv('./save_DataFrame.csv')

**[11장: 281페이지]**

In [18]:
!type './save_DataFrame.csv'

./save_DataFrame.csv not found


**[11장: 281페이지]**

In [19]:
df_pr = pd.DataFrame({'판매가격':[2000, 3000, 5000, 10000],
                       '판매량':[32, 53, 40, 25]},
                       index=['P1001', 'P1002', 'P1003', 'P1004'])

df_pr.index.name = '제품번호'
df_pr

판매가격  판매량
제품번호             
P1001   2000   32
P1002   3000   53
P1003   5000   40
P1004  10000   25

**[11장: 281페이지]**

In [20]:
file_name = './save_DataFrame_cp949.txt'
df_pr.to_csv(file_name, sep=" ", encoding = "cp949")

**[11장: 282페이지]**

In [25]:
!type ./save_DataFrame_cp949.txt

./save_DataFrame_cp949.txt not found


In [22]:
pwd

'/Users/Ahn/2023/Python/00. [교재]데이터분석을 위한 파이썬 철저 입문(위키북스)_20230428/notebook'

## 11.3 정리